### PR TITLE
Add One Shot Thrower support.

### PR DESCRIPTION
**Pull request by lpolasek**
Hi Samuel, I added _One Shot Thrower_ support, having all LEDs in the same strip.
Hope you like it

Best regards from Argentina...

### CODE REVIEW

**Comment by sbarabe** [comment]
Hi!

I'm away and busy for a while, I'll check your update as soon as I can, probably early September...

Hope you liked the architecture and your prop is working well. 

I'm working on a arm thrower in my spare time, I'm glad that I won't have to mingle with the code too much since you already had!

Cheers!

Samuel

**Comment by lpolasek** [comment]
Awesome, I loved your code, it just needed a little tweaking for make it
work in my Arm Thrower

Regards from Argentina...

**Comment by sbarabe** [comment]
So glad to ear that, that was the whole point of this code, make it easy to tweak for whatever projects, even other non GB related props.

I've only access to smartphone for a while and I can't review code on those devices, it drives me crazy. So I'll check your code in appropriate time.

Best regards from Canada!

**Comment by lpolasek** [comment]
Hi Samuel, were you able to review this pull request?
Regards...

**Comment by sbarabe** [comment]
Sorry I'm really busy right now and can't review this soon, hope to do it early September...

Thank.you for your patience!

Samuel

**Comment by sbarabe** [comment]
@lpolasek Hi Luis, I've check rapidly the code you have submitted. 

I'm not an advanced coder, just an enthusiast hobbyist, so basically could you explain what your did, like isCyclotronLed(j) function and other changes and how they are related with the arm thrower ?

Regards !

Samuel

**Comment by lpolasek** [comment]
Because I only use a single cyclotron light in the wand, attached to the same strip as the wand lights, cyclotron lights 2, 3 and 4 are not consecutive to light 1, so if I left the code as it is, the for loop turn off the wand lights in `update()` function.
This way, only the non-consecutive cyclotron lights are updated

I hope I explained it well

**Comment by lpolasek** [comment]
Hi Samuel, were you able to review this pull request?

Best regards...

**Comment by sbarabe** [comment]
Hi Luis,

I've check your code and decided not to merge it with the actual code because I prefer to leave this code to the Proton Pack and not mingle it with the wrist blaster (arm thrower). I'm glad you find a way to use this code for your prop easily because it is what it is intended for : easy to adapt.

The things I would be glad to add up in this code would be new animations and new devices for engines, like other players or leds drivers. 

I will leave the pack stages and general work flow as it is, and let people do their own workflow, like you did !

Thanks for submitting your code and idea!

PS I'm also working on an wrist blaster core I should put out I hope this winter.

**Comment by lpolasek** [comment]
Hi Samuel, thank you for your time on reviewing my code.
I'll wait for your wrist blaster code to see if it fit my needs

Best regards from Argentina...

**Pull request closed without merging**
